# fly.toml app configuration file generated for wandering-frost-5317 on 2024-10-11T16:45:44-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sequin-dev'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  hostname = '0.0.0.0'
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
